name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository to get the Dockerfile
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker Buildx using the latest action version
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (optional: only if pushing to a Docker registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build the Docker image
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

      # (Optional) Push the Docker image to a registry
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push my-image-name:$(date +%s)
