name: Build Docker Image
on:
  push:
    branches:
      - main
jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKER_HUB_USERNAME}}
            password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
          run: |
            docker login -u $username -p $password 
        - name: build the docker image
          id: build-docker-image
          run: docker build -t runpod-serverless .
        - name: Tag the Docker image
          run: |
            docker tag runpod-serverless-forked:latest-temp ${{ secrets.DOCKER_HUB_USERNAME}}/runpod-serverless:latest

        - name: push the docker image
          id: push-docker-image
          run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/runpod-serverless:latest
